# Generated by Django 4.1.7 on 2023-06-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tutorials', models.TextField(max_length=10000)),
                ('details', models.TextField(max_length=100000)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
