# Generated by Django 4.1.7 on 2023-06-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecialWish', models.TextField(blank=True, max_length=10000, null=True)),
                ('accept', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('pack1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack1')),
                ('pack10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack10')),
                ('pack2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack2')),
                ('pack3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack3')),
                ('pack4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack4')),
                ('pack5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack5')),
                ('pack6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack6')),
                ('pack7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack7')),
                ('pack8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack8')),
                ('pack9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack9')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
