# Generated by Django 4.1.7 on 2023-06-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='pack10',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='pack6',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='pack7',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='pack8',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='pack9',
        ),
        migrations.DeleteModel(
            name='Pack10',
        ),
        migrations.DeleteModel(
            name='Pack6',
        ),
        migrations.DeleteModel(
            name='Pack7',
        ),
        migrations.DeleteModel(
            name='Pack8',
        ),
        migrations.DeleteModel(
            name='Pack9',
        ),
    ]
