# Generated by Django 4.1.7 on 2023-06-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_offer_pack10_remove_offer_pack6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack1'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack2'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack3'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack4'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack5'),
        ),
        migrations.AddField(
            model_name='offer',
            name='pack6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack6'),
        ),
    ]
