# Generated by Django 4.1.7 on 2023-06-07 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pack7_pack8_pack9_alter_offer_pack6'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='pack7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack7'),
        ),
        migrations.AddField(
            model_name='offer',
            name='pack8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack8'),
        ),
        migrations.AddField(
            model_name='offer',
            name='pack9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack9'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack6'),
        ),
    ]
