# Generated by Django 4.1.7 on 2023-06-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_offer_pack7_offer_pack8_offer_pack9_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pack12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='pack10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack10'),
        ),
        migrations.AddField(
            model_name='offer',
            name='pack11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack11'),
        ),
        migrations.AddField(
            model_name='offer',
            name='pack12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack12'),
        ),
    ]
