# Generated by Django 4.1.7 on 2023-06-07 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_offer_pack1_alter_offer_pack10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack1',
            field=models.ForeignKey(blank=True, default='mid-level SEO', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack1'),
        ),
    ]
