# Generated by Django 4.1.7 on 2023-06-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_offer_email_offer_name_alter_offer_pack1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='pack1',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack1'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack2',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack2'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack3',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack3'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack4',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack4'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack5',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack5'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack6',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack6'),
        ),
    ]
