# Generated by Django 4.1.7 on 2023-06-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_offer_pack1_alter_offer_pack2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='pack10',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack10'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack11',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack11'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack7',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack7'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack8',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack8'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack9',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack9'),
        ),
    ]
