# Generated by Django 4.1.7 on 2023-06-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='accept',
            field=models.BooleanField(default=True),
        ),
    ]
