# Generated by Django 4.1.7 on 2023-06-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contact_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='package',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
